// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: calulator.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CalulatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *CalulatorRequest) Reset() {
	*x = CalulatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calulator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalulatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalulatorRequest) ProtoMessage() {}

func (x *CalulatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calulator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalulatorRequest.ProtoReflect.Descriptor instead.
func (*CalulatorRequest) Descriptor() ([]byte, []int) {
	return file_calulator_proto_rawDescGZIP(), []int{0}
}

func (x *CalulatorRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CalulatorRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type CalulatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CalulatorResponse) Reset() {
	*x = CalulatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calulator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalulatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalulatorResponse) ProtoMessage() {}

func (x *CalulatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calulator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalulatorResponse.ProtoReflect.Descriptor instead.
func (*CalulatorResponse) Descriptor() ([]byte, []int) {
	return file_calulator_proto_rawDescGZIP(), []int{1}
}

func (x *CalulatorResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_calulator_proto protoreflect.FileDescriptor

var file_calulator_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x6c, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2e, 0x0a, 0x10, 0x43, 0x61, 0x6c, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22,
	0x2b, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x4e, 0x0a, 0x09,
	0x43, 0x61, 0x6c, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x41, 0x0a, 0x09, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x43, 0x61, 0x6c, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x43, 0x61, 0x6c, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0d, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x07, 0x22, 0x02, 0x2f, 0x2a, 0x3a, 0x01, 0x2a, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calulator_proto_rawDescOnce sync.Once
	file_calulator_proto_rawDescData = file_calulator_proto_rawDesc
)

func file_calulator_proto_rawDescGZIP() []byte {
	file_calulator_proto_rawDescOnce.Do(func() {
		file_calulator_proto_rawDescData = protoimpl.X.CompressGZIP(file_calulator_proto_rawDescData)
	})
	return file_calulator_proto_rawDescData
}

var file_calulator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calulator_proto_goTypes = []interface{}{
	(*CalulatorRequest)(nil),  // 0: CalulatorRequest
	(*CalulatorResponse)(nil), // 1: CalulatorResponse
}
var file_calulator_proto_depIdxs = []int32{
	0, // 0: Calulator.Calculate:input_type -> CalulatorRequest
	1, // 1: Calulator.Calculate:output_type -> CalulatorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calulator_proto_init() }
func file_calulator_proto_init() {
	if File_calulator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calulator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalulatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calulator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalulatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calulator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calulator_proto_goTypes,
		DependencyIndexes: file_calulator_proto_depIdxs,
		MessageInfos:      file_calulator_proto_msgTypes,
	}.Build()
	File_calulator_proto = out.File
	file_calulator_proto_rawDesc = nil
	file_calulator_proto_goTypes = nil
	file_calulator_proto_depIdxs = nil
}
